name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [18]  # Specify a valid Node.js version here
    runs-on: ${{ matrix.platform }}
    env:
      PUPPETEER_SKIP_DOWNLOAD: false  # Remove this line if you want to download Chromium
      process.ci.env: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Cache Yarn packages
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
